import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "../styles/globals.css"
import Nav from "@/src/FE/components/utils/Nav";

const inter = Barlow_Condensed({weight:["400","900"] ,subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className+' overflow-x-hidden'}>
      <Nav authenticated={false} />
        {children}</body>
      <footer className="bg-black text-white py-8 text-center mt-20">
      © SOCIFIT Inc. 2023
      </footer>
    </html>
  );
}
